
cache:
  directories:
    - '$HOME/.composer/cache'

matrix:
    fast_finish: true
    include:
        -
            os: 'linux'
            dist: 'trusty'
            sudo: false
            language: 'php'
            php: '7.1'
#        -
#            os: 'osx'
#            language: 'generic'

before_install:
    - 'export COMPOSER_NO_INTERACTION=1'
    - 'export COMPOSER_DISABLE_XDEBUG_WARN=1'
    - 'export NVM_DIR="$HOME/.nvm"'
    - 'export NODE_VERSION="$(cat .nvmrc)"'
    - 'export PATH="${HOME}/.nvm/versions/node/v${NODE_VERSION}/bin/npm:${PATH}"'
    - 'export BREW_PHP=71'
    - 'src-dev/scripts/travis/before_install.sh'
    - 'nvm list'
    - 'nvm install "$NODE_VERSION"'
    - 'nvm use "$NODE_VERSION"'
    - 'nvm alias default "$NODE_VERSION"'
    - 'source "$NVM_DIR/nvm.sh"'
    - 'npm --version'
    - 'node --version'

install:
    - 'composer install --no-progress'

script:
    - 'bin/robo --ansi lint'
    - 'bin/robo --ansi test'

after_success:
    - 'bash <(curl -s https://codecov.io/bash)'

notifications:
    email: false
